spring:
  profiles:
    include: s3, jwt, mail
    active: local

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
---

spring:
  config:
    activate:
      on-profile: prod