name: Pull Request 시 테스트 결과 반환

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      # main 설정 파일 생성 및 write
      - name: make env file
        run: |
          # main 설정 파일 디렉토리로 이동
          cd ./src/main/resources
          
          # application-s3.yml 파일 생성
          touch ./application-s3.yml          
          # GitHub-Actions 에서 설정한 값을 application-s3.yml 파일에 쓰기
          echo "${{ secrets.S3 }}" >> ./application-s3.yml
          
          # application-mail.yml 파일 생성
          touch ./application-mail.yml          
          # GitHub-Actions 에서 설정한 값을 application-mail.yml 파일에 쓰기
          echo "${{ secrets.MAIL }}" >> ./application-mail.yml
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
         files: build/test-results/test/*.xml
